
const ITEMS=window.KNOWLEDGE_ITEMS||[];
const STORAGE_KEY='zsb-knowledge-pwa:v1';
const $=s=>document.querySelector(s);
const state={query:'',chapter:'',status:'',expanded:''};
let study=loadStudy(),deferredPrompt=null;
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function loadStudy(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}')}catch{return {}}}
function itemState(id){return study[id]||{read:false,starred:false,mastered:false,note:''}}
function setItemState(id,patch){study[id]={...itemState(id),...patch,updatedAt:new Date().toISOString()};localStorage.setItem(STORAGE_KEY,JSON.stringify(study));render()}
function chapters(){return [...new Set(ITEMS.map(i=>i.chapter))].sort((a,b)=>a.localeCompare(b,'zh-CN'))}
function searchText(i){return [i.id,i.title,i.chapter,i.range,i.batch,i.text,JSON.stringify(i.memoBlocks||[]),...(i.topics||[]),...(i.keywords||[])].join(' ')}
function matches(i){const st=itemState(i.id),q=state.query.trim().toLowerCase();if(state.chapter&&i.chapter!==state.chapter)return false;if(state.status==='unread'&&st.read)return false;if(state.status==='read'&&!st.read)return false;if(state.status==='starred'&&!st.starred)return false;if(state.status==='mastered'&&!st.mastered)return false;return !q||searchText(i).toLowerCase().includes(q)}
function list(lines,cls='list'){lines=(lines||[]).filter(Boolean);return lines.length?`<ul class="${cls}">${lines.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:'<p class="muted">暂无内容</p>'}
function preview(i){const b=(i.memoBlocks||[])[0];return b?(b.understanding||b.mustKnow||[]).slice(0,2):(i.outline||[]).slice(0,2)}
function answer(i){const a=(i.memoBlocks||[]).flatMap(b=>b.mustKnow||[]).slice(0,2);return a.length?a:(i.outline||[]).slice(0,2)}
function sec(t,lines,c){return `<section class="sec ${c||''}"><h4>${esc(t)}</h4>${list(lines)}</section>`}
function details(i){const bs=i.memoBlocks||[];if(!bs.length)return `<section class="sec"><h4>文字内容</h4><div class="raw">${esc(i.text||'暂无文字')}</div></section>`;return bs.map((b,n)=>`<div class="block"><div class="bhead"><span>${String(n+1).padStart(2,'0')}</span><strong>${esc(b.title||i.title)}</strong></div>${sec('怎么理解',b.understanding,'blue')}${sec('必背知识点',b.mustKnow,'green')}${sec('考试这样考',b.examPoints,'purple')}${sec('易混点',b.confusing,'orange')}${sec('记忆口诀',b.mnemonic,'yellow')}${sec('补充说明',b.supplement,'gray')}</div>`).join('')}
function media(i){const img=i.image?`<div class="imgbox"><img class="zoom" src="${esc(i.image)}" alt="${esc(i.title)}"></div>`:'';const pdf=i.pdf?`<a class="pdf" href="${esc(i.pdf)}" target="_blank" rel="noopener">打开原图 / PDF</a>`:'';return img||pdf?`<section class="media">${img}${pdf}</section>`:''}
function renderStats(){const vals=ITEMS.map(x=>itemState(x.id));$('#totalCount').textContent=ITEMS.length;$('#unreadCount').textContent=vals.filter(x=>!x.read).length;$('#starCount').textContent=vals.filter(x=>x.starred).length;$('#masteredCount').textContent=vals.filter(x=>x.mastered).length;document.querySelectorAll('.tabs button').forEach(b=>b.classList.toggle('active',b.dataset.status===state.status))}
function renderFilters(){const c=$('#chapterFilter'),cur=c.value;c.innerHTML='<option value="">全部章节</option>'+chapters().map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('');c.value=cur;$('#statusFilter').value=state.status}
function renderCards(){const arr=ITEMS.filter(matches).sort((a,b)=>(a.order||0)-(b.order||0));const feed=$('#feed');if(!arr.length){feed.innerHTML='<div class="empty">没有匹配结果</div>';return}feed.innerHTML=arr.map(i=>{const st=itemState(i.id),open=state.expanded===i.id;return `<article class="card ${open?'open':''}" data-id="${esc(i.id)}"><button class="title" data-act="toggle"><span class="num">${String(i.order||'').padStart(3,'0')}</span><span class="main"><b>${esc(i.title)}</b><em>${esc(i.chapter)} · ${esc(i.range||'')}</em></span><span class="arrow">${open?'收起':'展开'}</span></button><div class="pv"><div class="mini"><strong>怎么理解</strong>${list(preview(i),'plist')}</div><div class="mini ans"><strong>先背这个</strong>${list(answer(i),'plist')}</div></div><div class="ops"><button data-act="read" class="${st.read?'on':''}">${st.read?'已看':'标已看'}</button><button data-act="star" class="${st.starred?'on star':''}">${st.starred?'重点':'重点'}</button><button data-act="master" class="${st.mastered?'on master':''}">${st.mastered?'掌握':'掌握'}</button></div>${open?`<div class="full">${details(i)}${media(i)}<div class="note"><h4>我的笔记</h4><textarea data-note="${esc(i.id)}" placeholder="写自己的理解、易错点...">${esc(st.note||'')}</textarea></div></div>`:''}</article>`}).join('')}
function render(){renderStats();renderFilters();renderCards()}
document.addEventListener('click',e=>{const tab=e.target.closest('.tabs button');if(tab){state.status=tab.dataset.status;state.expanded='';render();return}const card=e.target.closest('.card');const act=e.target.closest('[data-act]')?.dataset.act;if(card&&act){const id=card.dataset.id,st=itemState(id);if(act==='toggle'){state.expanded=state.expanded===id?'':id;if(state.expanded&&!st.read){study[id]={...st,read:true,updatedAt:new Date().toISOString()};localStorage.setItem(STORAGE_KEY,JSON.stringify(study))}render();return}if(act==='read')setItemState(id,{read:!st.read});if(act==='star')setItemState(id,{starred:!st.starred});if(act==='master')setItemState(id,{mastered:!st.mastered,read:true});return}const img=e.target.closest('.zoom');if(img){$('#dialogImage').src=img.src;$('#imageDialog').showModal()}});
document.addEventListener('input',e=>{if(e.target.id==='searchInput'){state.query=e.target.value;renderCards();renderStats()}if(e.target.dataset.note){const id=e.target.dataset.note;study[id]={...itemState(id),note:e.target.value,updatedAt:new Date().toISOString()};localStorage.setItem(STORAGE_KEY,JSON.stringify(study))}});
$('#chapterFilter').addEventListener('change',e=>{state.chapter=e.target.value;state.expanded='';renderCards()});
$('#statusFilter').addEventListener('change',e=>{state.status=e.target.value;state.expanded='';render()});
$('#closeDialog').addEventListener('click',()=>$('#imageDialog').close());
$('#exportBtn').addEventListener('click',()=>{const blob=new Blob([JSON.stringify({version:1,exportedAt:new Date().toISOString(),study},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='专升本知识点学习记录.json';a.click();URL.revokeObjectURL(a.href)});
$('#importInput').addEventListener('change',async e=>{const f=e.target.files?.[0];if(!f)return;try{const data=JSON.parse(await f.text());study=data.study||data||{};localStorage.setItem(STORAGE_KEY,JSON.stringify(study));render();alert('导入完成')}catch{alert('导入失败，请选择正确 JSON')}});
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').classList.remove('hidden')});
$('#installBtn').addEventListener('click',async()=>{if(deferredPrompt){deferredPrompt.prompt();deferredPrompt=null;$('#installBtn').classList.add('hidden')}});
if('serviceWorker' in navigator){navigator.serviceWorker.register('./sw.js').catch(()=>{})}
render();
