
const ITEMS=window.KNOWLEDGE_ITEMS||[];
const STORAGE_KEY='zsb-knowledge-pwa:v1';
const $=s=>document.querySelector(s);
const state={query:'',chapter:'',status:'',selected:''};
let study=loadStudy(),deferredPrompt=null;
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function loadStudy(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}')}catch{return {}}}
function itemState(id){return study[id]||{read:false,starred:false,mastered:false,note:''}}
function setItemState(id,patch){study[id]={...itemState(id),...patch,updatedAt:new Date().toISOString()};localStorage.setItem(STORAGE_KEY,JSON.stringify(study));render()}
function chapters(){return [...new Set(ITEMS.map(i=>i.chapter))].sort((a,b)=>a.localeCompare(b,'zh-CN'))}
function textOf(i){return [i.id,i.title,i.chapter,i.range,i.batch,i.text,JSON.stringify(i.memoBlocks||[]),...(i.topics||[]),...(i.keywords||[])].join(' ')}
function matches(i){const st=itemState(i.id),q=state.query.trim().toLowerCase();if(state.chapter&&i.chapter!==state.chapter)return false;if(state.status==='unread'&&st.read)return false;if(state.status==='read'&&!st.read)return false;if(state.status==='starred'&&!st.starred)return false;if(state.status==='mastered'&&!st.mastered)return false;return !q||textOf(i).toLowerCase().includes(q)}
function filtered(){return ITEMS.filter(matches).sort((a,b)=>(a.order||0)-(b.order||0))}
function list(lines){lines=(lines||[]).filter(Boolean);return lines.length?`<ul>${lines.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:'<p class="muted">暂无内容</p>'}
function quick(i){const b=(i.memoBlocks||[])[0];return b?(b.understanding||b.mustKnow||[]).slice(0,1):(i.outline||[]).slice(0,1)}
function must(i){const a=(i.memoBlocks||[]).flatMap(b=>b.mustKnow||[]).slice(0,1);return a.length?a:(i.outline||[]).slice(0,1)}
function section(title,lines,open=false,cls=''){return `<details class="sec ${cls}" ${open?'open':''}><summary>${esc(title)}</summary>${list(lines)}</details>`}
function blocksHTML(i){const bs=i.memoBlocks||[];if(!bs.length)return `<details class="sec" open><summary>文字内容</summary><div class="raw">${esc(i.text||'暂无文字')}</div></details>`;return bs.map((b,idx)=>`<div class="block"><div class="block-title"><span>${String(idx+1).padStart(2,'0')}</span><strong>${esc(b.title||i.title)}</strong></div>${section('怎么理解',b.understanding,true,'blue')}${section('必背知识点',b.mustKnow,true,'green')}${section('考试这样考',b.examPoints,false,'purple')}${section('易混点',b.confusing,false,'orange')}${section('记忆口诀',b.mnemonic,false,'yellow')}${section('补充说明',b.supplement,false,'gray')}</div>`).join('')}
function media(i){const img=i.image?`<div class="imgbox"><img class="zoom" src="${esc(i.image)}" alt="${esc(i.title)}"></div>`:'';const pdf=i.pdf?`<a class="pdf" href="${esc(i.pdf)}" target="_blank" rel="noopener">打开原图 / PDF</a>`:'';return img||pdf?`<section class="media">${img}${pdf}</section>`:''}
function sourceHTML(i){const hasText=(i.text||'').trim();const raw=hasText?`<details class="sec raw-sec"><summary>完整资料文字 / OCR 原文</summary><div class="raw">${esc(i.text)}</div></details>`:`<details class="sec raw-sec"><summary>完整资料文字 / OCR 原文</summary><p class="muted">暂无 OCR 文字，请打开原图或 PDF 核对。</p></details>`;const src=media(i);return `<section class="source-card"><h3>完整资料</h3><p class="source-tip">这里保留原图/PDF和完整文字。不是删掉了，默认收起来是为了手机背诵不太长。</p>${src}${raw}</section>`}
function renderStats(){const vals=ITEMS.map(i=>itemState(i.id));$('#totalCount').textContent=ITEMS.length;$('#unreadCount').textContent=vals.filter(x=>!x.read).length;$('#starCount').textContent=vals.filter(x=>x.starred).length;$('#masteredCount').textContent=vals.filter(x=>x.mastered).length;document.querySelectorAll('.tabs button').forEach(b=>b.classList.toggle('active',b.dataset.status===state.status))}
function renderFilters(){const c=$('#chapterFilter'),cur=c.value;c.innerHTML='<option value="">全部章节</option>'+chapters().map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('');c.value=cur;$('#statusFilter').value=state.status}
function renderList(){const arr=filtered();$('#shownCount').textContent=arr.length; if(!arr.length){$('#itemList').innerHTML='<div class="nores">没有匹配结果</div>';return} if(!state.selected||!arr.some(i=>i.id===state.selected)) state.selected=arr[0].id; $('#itemList').innerHTML=arr.map(i=>{const st=itemState(i.id);return `<button class="row ${i.id===state.selected?'active':''}" data-id="${esc(i.id)}"><span class="num">${String(i.order||'').padStart(3,'0')}</span><span class="rmain"><b>${esc(i.title)}</b><em>${esc(i.chapter)} · ${esc(i.range||'')}</em><small>${esc((quick(i)[0]||'').slice(0,48))}</small></span><span class="marks">${st.starred?'★':''}${st.mastered?'✓':''}</span></button>`}).join('')}
function renderDetail(){const i=ITEMS.find(x=>x.id===state.selected);const pane=$('#detailPane');if(!i){pane.innerHTML='<div class="empty">点一个知识点开始背。</div>';return} const st=itemState(i.id);pane.innerHTML=`<button class="back" id="backBtn">← 返回列表</button><div class="dhead"><div><p>${esc(i.chapter)} · ${esc(i.range||'')}</p><h2>${esc(i.title)}</h2></div><span>${String(i.order||'').padStart(3,'0')}</span></div><div class="quick"><div><strong>怎么理解</strong>${list(quick(i))}</div><div><strong>先背这个</strong>${list(must(i))}</div></div><div class="dops"><button data-act="read" class="${st.read?'on':''}">${st.read?'已看':'标已看'}</button><button data-act="star" class="${st.starred?'on star':''}">${st.starred?'重点':'重点'}</button><button data-act="master" class="${st.mastered?'on master':''}">${st.mastered?'掌握':'掌握'}</button></div>${blocksHTML(i)}${sourceHTML(i)}<div class="note"><h3>我的笔记</h3><textarea data-note="${esc(i.id)}" placeholder="写自己的理解、易错点...">${esc(st.note||'')}</textarea></div>`;document.body.classList.add('detail-mode')}
function render(){renderStats();renderFilters();renderList();renderDetail()}
document.addEventListener('click',e=>{const tab=e.target.closest('.tabs button');if(tab){state.status=tab.dataset.status;state.selected='';render();return}const row=e.target.closest('.row');if(row){state.selected=row.dataset.id;const st=itemState(state.selected);if(!st.read){study[state.selected]={...st,read:true,updatedAt:new Date().toISOString()};localStorage.setItem(STORAGE_KEY,JSON.stringify(study))}renderList();renderDetail();return}if(e.target.id==='backBtn'){document.body.classList.remove('detail-mode');return}const act=e.target.closest('[data-act]')?.dataset.act;if(act&&state.selected){const st=itemState(state.selected);if(act==='read')setItemState(state.selected,{read:!st.read});if(act==='star')setItemState(state.selected,{starred:!st.starred});if(act==='master')setItemState(state.selected,{mastered:!st.mastered,read:true});return}const img=e.target.closest('.zoom');if(img){$('#dialogImage').src=img.src;$('#imageDialog').showModal()}});
document.addEventListener('input',e=>{if(e.target.id==='searchInput'){state.query=e.target.value;state.selected='';renderList();renderDetail()}if(e.target.dataset.note){const id=e.target.dataset.note;study[id]={...itemState(id),note:e.target.value,updatedAt:new Date().toISOString()};localStorage.setItem(STORAGE_KEY,JSON.stringify(study))}});
$('#chapterFilter').addEventListener('change',e=>{state.chapter=e.target.value;state.selected='';renderList();renderDetail()});
$('#statusFilter').addEventListener('change',e=>{state.status=e.target.value;state.selected='';render()});
$('#closeDialog').addEventListener('click',()=>$('#imageDialog').close());
$('#exportBtn').addEventListener('click',()=>{const blob=new Blob([JSON.stringify({version:1,exportedAt:new Date().toISOString(),study},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='专升本知识点学习记录.json';a.click();URL.revokeObjectURL(a.href)});
$('#importInput').addEventListener('change',async e=>{const f=e.target.files?.[0];if(!f)return;try{const data=JSON.parse(await f.text());study=data.study||data||{};localStorage.setItem(STORAGE_KEY,JSON.stringify(study));render();alert('导入完成')}catch{alert('导入失败，请选择正确 JSON')}});
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').classList.remove('hidden')});
$('#installBtn').addEventListener('click',async()=>{if(deferredPrompt){deferredPrompt.prompt();deferredPrompt=null;$('#installBtn').classList.add('hidden')}});
if('serviceWorker'in navigator){navigator.serviceWorker.register('./sw.js').catch(()=>{})}
render();
